install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
    system(`sh "./CallDetailsHistory/Supporting Files/unzip-react.sh" --pods-path="./Pods/OCE"`)
end

target 'CallDetailsHistory' do
  use_frameworks!
  pod 'OCE', :git => "https://${USER_NAME}:${OCE_TOKEN}@gitlab.ims.io/oce/oce-apps-framework", :tag => "10.0.5"
end
