install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
    system("
      node './Pods/OCE/ocescripts/compareVersionsBetweenPodfileAndPackageJson.js' './Podfile' `find . -maxdepth 3 -iname package.json`
    ")

	installer.pods_project.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['SUPPORTS_MACCATALYST'] = 'NO'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['ARCHS'] = '${ARCHS_STANDARD_64_BIT}'
    end
end

target 'PlanCycleSummary' do
  use_frameworks!
  pod 'OCE', :git => "https://${USER_NAME}:${OCE_TOKEN}@gitlab.ims.io/oce/oce-apps-framework", :tag => "20.0.0"
end
