export const FETCH_SPEAKERS_DATA = [
  {
    Id: 'a4v040000000MakAAE',
    Name: 'Test speaker 1',
    professionalDesignation: null,
    specialty: null,
    status: null,
  },
  {
    Id: 'a4v0400000003ReAAI',
    Name: '0 1 HCP',
    professionalDesignation: 'DO;MBBS;MD',
    specialty: 'Adolescent medicine',
    status: 'Nominated',
  },
  {
    Id: 'a4v0400000003RUAAY',
    Name: '0 2 Acc',
    professionalDesignation: null,
    specialty: 'Addiction medicine',
    status: 'Nominated',
  },
  {
    Id: 'a4v6g000000qLrgAAE',
    Name: 'Test speaker 4',
    professionalDesignation: null,
    specialty: 'Advanced heart failure and transplant ca',
    status: 'Nominated',
  },
  {
    Id: 'a4v6g000000qFaRAAU',
    Name: '111 XXX Medical Pro',
    professionalDesignation: null,
    specialty: 'Adult cardiothoracic anesthesiology',
    status: 'Nominated',
  },
  {
    Id: 'a4v6g000000R03oAAC',
    Name: 'AARON BOWEN',
    professionalDesignation: null,
    specialty: 'Internal medicine',
    status: 'Nominated',
  },
  {
    Id: 'a4v6g000000R03pAAC',
    Name: 'AARON MORITA',
    professionalDesignation: null,
    specialty: 'Internal medicine',
    status: 'Nominated',
  },
  {
    Id: 'a4v040000000kYPAAY',
    Name: 'AARON MORITA',
    professionalDesignation: null,
    specialty: 'Addiction medicine',
    status: null,
  },
  {
    Id: 'a4v6g000001Iov4AAC',
    Name: 'AARON VENTI',
    professionalDesignation: null,
    specialty: 'Family medicine',
    status: 'Nominated',
  },
  {
    Id: 'a4v040000000kTZAAY',
    Name: 'Account Customer02',
    professionalDesignation: null,
    specialty: 'Alternate therapy',
    status: null,
  },
  {
    Id: 'a4v040000000kTyAAI',
    Name: 'Account Customer02',
    professionalDesignation: null,
    specialty: 'Alternate therapy',
    status: null,
  },
  {
    Id: 'a4v040000000kTFAAY',
    Name: 'Account Customer03',
    professionalDesignation: null,
    specialty: 'Diabetes',
    status: 'Active',
  },
  {
    Id: 'a4v040000000kTjAAI',
    Name: 'Account Customer04',
    professionalDesignation: null,
    specialty: 'Dentist',
    status: null,
  },
  {
    Id: 'a4v040000000kTKAAY',
    Name: 'Account Customer05',
    professionalDesignation: null,
    specialty: 'Family medicine',
    status: 'Active',
  },
  {
    Id: 'a4v040000000kToAAI',
    Name: 'Account Customer06',
    professionalDesignation: null,
    specialty: 'Addiction medicine',
    status: null,
  },
];

export const FETCH_MORE_SPEAKERS_DATA = [
  {
    Id: 'a4v040000000kUXAAY',
    Name: 'Account Customer12',
    professionalDesignation: null,
    specialty: 'Alternate therapy',
    status: null,
  },
  {
    Id: 'a4v040000000kUcAAI',
    Name: 'Account Customer13',
    professionalDesignation: null,
    specialty: 'Dentist',
    status: null,
  },
  {
    Id: 'a4v040000000kUhAAI',
    Name: 'Account Customer14',
    professionalDesignation: null,
    specialty: 'Dentistry/orthodontics',
    status: null,
  },
  {
    Id: 'a4v040000000mOBAAY',
    Name: 'Account DC OO 1',
    professionalDesignation: 'DO',
    specialty: 'Adolescent medicine',
    status: 'Nominated',
  },
  {
    Id: 'a4v6g000001IoufAAC',
    Name: 'Adele Medical Professionals',
    professionalDesignation: null,
    specialty: 'Abdominal radiology',
    status: 'Nominated',
  },
  {
    Id: 'a4v6g000001IoujAAC',
    Name: 'Adeles Medical Professionals',
    professionalDesignation: null,
    specialty: 'Abdominal radiology',
    status: 'Nominated',
  },
  {
    Id: 'a4v6g000000qFaVAAU',
    Name: 'AFSHINE GHAEMI',
    professionalDesignation: null,
    specialty: 'Family medicine',
    status: 'Nominated',
  },
  {
    Id: 'a4v040000000MbEAAU',
    Name: 'ALISON JOHNSON',
    professionalDesignation: null,
    specialty: null,
    status: null,
  },
  {
    Id: 'a4v0400000003IaAAI',
    Name: 'ALISON MCORD T',
    professionalDesignation: null,
    specialty: 'Abdominal radiology',
    status: 'Nominated',
  },
  {
    Id: 'a4v6g000001Ip3dAAC',
    Name: 'AMER RAHMAN',
    professionalDesignation: null,
    specialty: 'Endocrinology',
    status: 'Nominated',
  },
  {
    Id: 'a4v0400000003IfAAI',
    Name: 'AMILE JACKSON',
    professionalDesignation: null,
    specialty: 'Abdominal radiology',
    status: 'Nominated',
  },
  {
    Id: 'a4v6g000001AZqVAAW',
    Name: 'ASHOK KUMAR',
    professionalDesignation: null,
    specialty: 'Facial plastic surgery',
    status: 'Nominated',
  },
  {
    Id: 'a4v6g000000qLrNAAU',
    Name: 'ATF Restricted_V_1',
    professionalDesignation: null,
    specialty: 'Acupuncturist',
    status: 'Nominated',
  },
  {
    Id: 'a4v6g000000qLrSAAU',
    Name: 'ATF Restricted_V_2',
    professionalDesignation: null,
    specialty: 'Addiction psychiatry',
    status: 'Nominated',
  },
  {
    Id: 'a4v6g000000qLrXAAU',
    Name: 'ATF Restricted_V_3_Allow',
    professionalDesignation: null,
    specialty: 'Addiction medicine',
    status: 'Nominated',
  },
];

export const SEARCH_SPEAKERS_DATA = [
  {
    Id: 'a4v6g000000qLrbAAE',
    Name: 'Ziad Attar',
    professionalDesignation: null,
    specialty: null,
    status: 'Nominated',
  },
];
