install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
    system("sh './MeetingPulse/Supporting Files/unzip-react.sh' --pods-path='./Pods/OCE'")
end

target 'MeetingPulse' do
  use_frameworks!
  pod 'OCE', :git => "https://${USER_NAME}:${OCE_TOKEN}@gitlab.ims.io/oce/oce-apps-framework", :tag => "15.0.2"
end
