import { NAMESPACE } from './namespacePrefix';

export const FETCH_MEETING_RESPONSE = [
  [
    {
      Id: 'a3c04000000Gs0UAAS',
      [`${NAMESPACE}StartDateTime__c`]: '2021-05-31T12:47:58.000+0000',
      [`${NAMESPACE}ContextUserRole__c`]: 'Org',
      uid: 'a3c04000000Gs0UAAS',
    },
  ],
];

export const MAPPED_MEETING = {
  OCE__StartDateTime__c: '2021-05-31T12:47:58.000+0000',
  uid: 'a3c04000000Gs0UAAS',
  OCE__ContextUserRole__c: 'Org',
  id: 'a3c04000000Gs0UAAS',
};

export const FETCH_RECORD_TYPE_RESPONSE = [[{ Id: '0126g000000LvxTAAS', uid: '0126g000000LvxTAAS' }]];

export const MAPPED_RECORD_TYPE = { id: '0126g000000LvxTAAS' };

export const FETCH_MEETING_MEMBERS_RESPONSE = [
  [
    {
      CreatedDate: '2021-07-21T15:06:28.000+0000',
      Id: 'a3Y04000000Gq2oEAC',
      Name: '- / AHSAN',
      [`${NAMESPACE}Speaker__c`]: 'a4v040000000MakAAE',
      uid: 'a3Y04000000Gq2oEAC',
    },
  ],
];

export const MAPPED_MEETING_MEMBERS = [
  {
    CreatedDate: '2021-07-21T15:06:28.000+0000',
    Id: 'a3Y04000000Gq2oEAC',
    Name: '- / AHSAN',
    OCE__Speaker__c: 'a4v040000000MakAAE',
    uid: 'a3Y04000000Gq2oEAC',
    id: 'a3Y04000000Gq2oEAC',
    speaker: 'a4v040000000MakAAE',
    name: '- / AHSAN',
  },
];

export const FETCH_USER_PREFERRED_COUNTRIES_RESPONSE = [
  [{ QIDC__MDM_Preferred_Country_ims__c: 'AT', uid: '0056g000002f4neAAA' }],
];
export const FETCH_SPEAKERS_DATA = [
  {
    Id: 'a4v040000000MakAAE',
    Name: 'Test speaker 1',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: null,
    [`${NAMESPACE}Status__c`]: null,
  },
  {
    Id: 'a4v0400000003ReAAI',
    Name: '0 1 HCP',
    [`${NAMESPACE}ProfessionalDesignation__c`]: 'DO;MBBS;MD',
    [`${NAMESPACE}Specialty__c`]: 'Adolescent medicine',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v0400000003RUAAY',
    Name: '0 2 Acc',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Addiction medicine',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v6g000000qLrgAAE',
    Name: 'Test speaker 4',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Advanced heart failure and transplant ca',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v6g000000qFaRAAU',
    Name: '111 XXX Medical Pro',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Adult cardiothoracic anesthesiology',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v6g000000R03oAAC',
    Name: 'AARON BOWEN',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Internal medicine',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v6g000000R03pAAC',
    Name: 'AARON MORITA',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Internal medicine',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v040000000kYPAAY',
    Name: 'AARON MORITA',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Addiction medicine',
    [`${NAMESPACE}Status__c`]: null,
  },
  {
    Id: 'a4v6g000001Iov4AAC',
    Name: 'AARON VENTI',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Family medicine',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v040000000kTZAAY',
    Name: 'Account Customer02',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Alternate therapy',
    [`${NAMESPACE}Status__c`]: null,
  },
  {
    Id: 'a4v040000000kTyAAI',
    Name: 'Account Customer02',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Alternate therapy',
    [`${NAMESPACE}Status__c`]: null,
  },
  {
    Id: 'a4v040000000kTFAAY',
    Name: 'Account Customer03',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Diabetes',
    [`${NAMESPACE}Status__c`]: 'Active',
  },
  {
    Id: 'a4v040000000kTjAAI',
    Name: 'Account Customer04',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Dentist',
    [`${NAMESPACE}Status__c`]: null,
  },
  {
    Id: 'a4v040000000kTKAAY',
    Name: 'Account Customer05',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Family medicine',
    [`${NAMESPACE}Status__c`]: 'Active',
  },
  {
    Id: 'a4v040000000kToAAI',
    Name: 'Account Customer06',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Addiction medicine',
    [`${NAMESPACE}Status__c`]: null,
  },
];
export const FETCH_MORE_SPEAKERS_DATA = [
  {
    Id: 'a4v040000000kUXAAY',
    Name: 'Account Customer12',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Alternate therapy',
    [`${NAMESPACE}Status__c`]: null,
  },
  {
    Id: 'a4v040000000kUcAAI',
    Name: 'Account Customer13',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Dentist',
    [`${NAMESPACE}Status__c`]: null,
  },
  {
    Id: 'a4v040000000kUhAAI',
    Name: 'Account Customer14',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Dentistry/orthodontics',
    [`${NAMESPACE}Status__c`]: null,
  },
  {
    Id: 'a4v040000000mOBAAY',
    Name: 'Account DC OO 1',
    [`${NAMESPACE}ProfessionalDesignation__c`]: 'DO',
    [`${NAMESPACE}Specialty__c`]: 'Adolescent medicine',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v6g000001IoufAAC',
    Name: 'Adele Medical Professionals',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Abdominal radiology',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v6g000001IoujAAC',
    Name: 'Adeles Medical Professionals',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Abdominal radiology',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v6g000000qFaVAAU',
    Name: 'AFSHINE GHAEMI',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Family medicine',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v040000000MbEAAU',
    Name: 'ALISON JOHNSON',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: null,
    [`${NAMESPACE}Status__c`]: null,
  },
  {
    Id: 'a4v0400000003IaAAI',
    Name: 'ALISON MCORD T',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Abdominal radiology',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v6g000001Ip3dAAC',
    Name: 'AMER RAHMAN',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Endocrinology',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v0400000003IfAAI',
    Name: 'AMILE JACKSON',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Abdominal radiology',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v6g000001AZqVAAW',
    Name: 'ASHOK KUMAR',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Facial plastic surgery',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v6g000000qLrNAAU',
    Name: 'ATF Restricted_V_1',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Acupuncturist',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v6g000000qLrSAAU',
    Name: 'ATF Restricted_V_2',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Addiction psychiatry',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
  {
    Id: 'a4v6g000000qLrXAAU',
    Name: 'ATF Restricted_V_3_Allow',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: 'Addiction medicine',
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
];
export const SEARCH_SPEAKERS_DATA = [
  {
    Id: 'a4v6g000000qLrbAAE',
    Name: 'Ziad Attar',
    [`${NAMESPACE}ProfessionalDesignation__c`]: null,
    [`${NAMESPACE}Specialty__c`]: null,
    [`${NAMESPACE}Status__c`]: 'Nominated',
  },
];
export const MAPPED_SPEAKERS = [
  {
    id: 'a4v040000000MakAAE',
    name: 'Test speaker 1',
    account: undefined,
    specialty: null,
    professionalDesignation: null,
    status: null,
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v0400000003ReAAI',
    name: '0 1 HCP',
    account: undefined,
    specialty: 'Adolescent medicine',
    professionalDesignation: 'DO;MBBS;MD',
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v0400000003RUAAY',
    name: '0 2 Acc',
    account: undefined,
    specialty: 'Addiction medicine',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000000qLrgAAE',
    name: 'Test speaker 4',
    account: undefined,
    specialty: 'Advanced heart failure and transplant ca',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000000qFaRAAU',
    name: '111 XXX Medical Pro',
    account: undefined,
    specialty: 'Adult cardiothoracic anesthesiology',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000000R03oAAC',
    name: 'AARON BOWEN',
    account: undefined,
    specialty: 'Internal medicine',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000000R03pAAC',
    name: 'AARON MORITA',
    account: undefined,
    specialty: 'Internal medicine',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v040000000kYPAAY',
    name: 'AARON MORITA',
    account: undefined,
    specialty: 'Addiction medicine',
    professionalDesignation: null,
    status: null,
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000001Iov4AAC',
    name: 'AARON VENTI',
    account: undefined,
    specialty: 'Family medicine',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v040000000kTZAAY',
    name: 'Account Customer02',
    account: undefined,
    specialty: 'Alternate therapy',
    professionalDesignation: null,
    status: null,
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v040000000kTyAAI',
    name: 'Account Customer02',
    account: undefined,
    specialty: 'Alternate therapy',
    professionalDesignation: null,
    status: null,
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v040000000kTFAAY',
    name: 'Account Customer03',
    account: undefined,
    specialty: 'Diabetes',
    professionalDesignation: null,
    status: 'Active',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v040000000kTjAAI',
    name: 'Account Customer04',
    account: undefined,
    specialty: 'Dentist',
    professionalDesignation: null,
    status: null,
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v040000000kTKAAY',
    name: 'Account Customer05',
    account: undefined,
    specialty: 'Family medicine',
    professionalDesignation: null,
    status: 'Active',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v040000000kToAAI',
    name: 'Account Customer06',
    account: undefined,
    specialty: 'Addiction medicine',
    professionalDesignation: null,
    status: null,
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
];
export const MAPPED_MORE_SPEAKERS = [
  {
    id: 'a4v040000000kUXAAY',
    name: 'Account Customer12',
    account: undefined,
    specialty: 'Alternate therapy',
    professionalDesignation: null,
    status: null,
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v040000000kUcAAI',
    name: 'Account Customer13',
    account: undefined,
    specialty: 'Dentist',
    professionalDesignation: null,
    status: null,
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v040000000kUhAAI',
    name: 'Account Customer14',
    account: undefined,
    specialty: 'Dentistry/orthodontics',
    professionalDesignation: null,
    status: null,
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v040000000mOBAAY',
    name: 'Account DC OO 1',
    account: undefined,
    specialty: 'Adolescent medicine',
    professionalDesignation: 'DO',
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000001IoufAAC',
    name: 'Adele Medical Professionals',
    account: undefined,
    specialty: 'Abdominal radiology',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000001IoujAAC',
    name: 'Adeles Medical Professionals',
    account: undefined,
    specialty: 'Abdominal radiology',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000000qFaVAAU',
    name: 'AFSHINE GHAEMI',
    account: undefined,
    specialty: 'Family medicine',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v040000000MbEAAU',
    name: 'ALISON JOHNSON',
    account: undefined,
    specialty: null,
    professionalDesignation: null,
    status: null,
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v0400000003IaAAI',
    name: 'ALISON MCORD T',
    account: undefined,
    specialty: 'Abdominal radiology',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000001Ip3dAAC',
    name: 'AMER RAHMAN',
    account: undefined,
    specialty: 'Endocrinology',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v0400000003IfAAI',
    name: 'AMILE JACKSON',
    account: undefined,
    specialty: 'Abdominal radiology',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000001AZqVAAW',
    name: 'ASHOK KUMAR',
    account: undefined,
    specialty: 'Facial plastic surgery',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000000qLrNAAU',
    name: 'ATF Restricted_V_1',
    account: undefined,
    specialty: 'Acupuncturist',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000000qLrSAAU',
    name: 'ATF Restricted_V_2',
    account: undefined,
    specialty: 'Addiction psychiatry',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
  {
    id: 'a4v6g000000qLrXAAU',
    name: 'ATF Restricted_V_3_Allow',
    account: undefined,
    specialty: 'Addiction medicine',
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
];
export const MAPPED_SEARCH_SPEAKERS = [
  {
    id: 'a4v6g000000qLrbAAE',
    name: 'Ziad Attar',
    account: undefined,
    specialty: null,
    professionalDesignation: null,
    status: 'Nominated',
    user: undefined,
    allowRestrictedProducts: undefined,
    accountId: undefined,
  },
];
